### ISSUE TITLE
Feedback From Collogues 

### ISSUE THREAD

**Issue by shah-shuja-dev** [melashu/School-Project#3]
### Feedback From David Kasillia.

 - Add Linters.
- Instead of using dead links for the videos, you can use an iframe for faster loading time. 
-   Use good HTML Semitics, Define the Header, main, and footer of your site.
-   Good Work on overall responsiveness.

### Feedback From Blossom Aneidi.

- Great use of HTML semantics tags, There are no Linter Errors.
- The picture is a bit blur kindly fix it.

### Feedback From Shuja. 
Your website is impressive, it was so hard to find anything that I didn't like,
however here are a few suggestions from me and our team to make it more
better.
```
     <div class="container">
            <button class="btn">Continue as Facebook</button>
            <button class="btn">Continue as Google</button>
            <button class="btn">Continue as Twetter</button>
        </div>
```

- Please Add a <a> tag here to specify that these buttons are links also please fix the twitter spell :D .

**Comment by melashu** [comment]
Thanks my team for your constructive feedback.
